# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a1e6691c28c4e8315c25b89ba33923b92be915469465c5ca4799d07afa2d4d7fb7a35ac84dc4118d83189b7692ef3d251535f5d28ca38c78e78e3550cf44d98

test:
  secret_key_base: 2928af31c98731e1448b478aafd9a88b12cc96527c1ff2afaebc373f4d0f0c405e1b0a6afa341b862dd0e50f41187891828a51b4725fcc559ab463c9467e2a4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
